server:
  port: 8085

spring:
  data:
    mongodb:
      uri: mongodb://mongo-notification-service:27017/notification-servicedb

service:
  api-key: 7f30596e43ac7f5e9b902c7728dffbe5

springdoc:
  swagger-ui:
    path: /swagger-ui.html
