server:
  port: 8086

spring:
  data:
    mongodb:
      uri: mongodb://mongo-payment-service:27017/payment-servicedb

service:
  api-key: 8e5ca88f08921358127efe705aa1cd25

springdoc:
  swagger-ui:
    path: /swagger-ui.html
