server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://mongo-order-service:27017/order-servicedb

service:
  api-key: 70f5b2a758bbc21962080b0b281934f6

springdoc:
  swagger-ui:
    path: /swagger-ui.html
