server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://mongo-restaurant-service:27017/restaurant-servicedb

service:
  api-key: 5d9ed270ef016a016b30027645689ffe

springdoc:
  swagger-ui:
    path: /swagger-ui.html
