server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb://mongo-delivery-service:27017/delivery-servicedb

service:
  api-key: ab9e48196b29810d80991601bb850d33

springdoc:
  swagger-ui:
    path: /swagger-ui.html
